services:
  postgres:
    image: postgres:16-alpine
    container_name: barBot_postgres
    environment:
      POSTGRES_USER: ${DBUSER}
      POSTGRES_PASSWORD: ${DBPASS}
      POSTGRES_DB: ${DBNAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - barBot_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DBUSER} -d ${DBNAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  barBot_network:
    external: true
